<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="CryptoSoft\**" />
    <EmbeddedResource Remove="CryptoSoft\**" />
    <None Remove="CryptoSoft\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.2.7" />
    <PackageReference Include="Avalonia.Desktop" Version="11.2.7" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.2.7" />
  </ItemGroup>
  <ItemGroup>
    <AvaloniaXaml Include="**\*.xaml" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Resources\Languages\*.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
  <Reference Include="EasyLog">
    <HintPath>lib\EasyLog.dll</HintPath>
  </Reference>
</ItemGroup>

  <Target Name="CopyCryptoSoft" AfterTargets="Build">
    <MSBuild Projects="CryptoSoft\CryptoSoft.csproj"
             Properties="Configuration=$(Configuration);Platform=AnyCPU"
             Targets="Build" />
    <Copy SourceFiles="CryptoSoft\bin\$(Configuration)\net9.0\CryptoSoft.exe;CryptoSoft\bin\$(Configuration)\net9.0\CryptoSoft.dll;CryptoSoft\bin\$(Configuration)\net9.0\CryptoSoft.deps.json;CryptoSoft\bin\$(Configuration)\net9.0\CryptoSoft.runtimeconfig.json"
          DestinationFolder="$(OutputPath)"
          SkipUnchangedFiles="true" />
  </Target>

</Project>
