<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<None Update="Resources\*.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>
  <ItemGroup>
  <Reference Include="EasyLog">
    <HintPath>lib\EasyLog.dll</HintPath>
  </Reference>
</ItemGroup>
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Resources\Languages\" />
  </ItemGroup>

</Project>
